apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{- $existing := (lookup "apps/v1" "Deployment" .Release.Namespace .Release.Name) }}
{{- if $existing }}
{{ toYaml $existing.spec.selector.matchLabels | indent 6 }}
{{- else }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: nginx
{{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80