# --- Rollout: App A ---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-a
  namespace: demo-mesh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
  spec:
    containers:
      - name: app-a
        image: argoproj/rollouts-demo:blue
        ports:
          - containerPort: 8080
  strategy:
    canary:
      stableService: app-a-stable
      canaryService: app-a-canary
      trafficRouting:
        istio:
          virtualService:
            name: app-a-vs
            routes:
              - http
      steps:
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100

---
# --- Services for App A ---
apiVersion: v1
kind: Service
metadata:
  name: app-a-stable
  namespace: demo-mesh
spec:
  selector:
    app: app-a
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app-a-canary
  namespace: demo-mesh
spec:
  selector:
    app: app-a
  ports:
    - port: 80
      targetPort: 8080

---
# --- Istio for App A ---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-a-vs
  namespace: demo-mesh
spec:
  hosts:
    - app-a.local
  http:
    - route:
        - destination:
            host: app-a-stable
          weight: 100
        - destination:
            host: app-a-canary
          weight: 0

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-a-dr
  namespace: demo-mesh
spec:
  host: app-a-stable
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-a-canary-dr
  namespace: demo-mesh
spec:
  host: app-a-canary