# --- Rollout: App A ---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-a
  namespace: demo-mesh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
        version: stable
    spec:
      containers:
        - name: app-a
          image: argoproj/rollouts-demo:blue
          ports:
            - containerPort: 8080
  strategy:
    canary:
      stableService: app-a-stable
      canaryService: app-a-canary
      trafficRouting:
        istio:
          virtualService:
            name: app-a-vs
            routes:
              - http
      steps:
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100

---
# --- Services for App A ---
apiVersion: v1
kind: Service
metadata:
  name: app-a-stable
  namespace: demo-mesh
spec:
  selector:
    app: app-a
    version: stable
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app-a-canary
  namespace: demo-mesh
spec:
  selector:
    app: app-a
    version: canary
  ports:
    - port: 80
      targetPort: 8080

---
# --- Istio for App A ---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-a-vs
  namespace: demo-mesh
spec:
  hosts:
    - app-a.demo-mesh.svc.cluster.local
  http:
    - route:
        - destination:
            host: app-a.demo-mesh.svc.cluster.local
            subset: stable
          weight: 100
        - destination:
            host: app-a.demo-mesh.svc.cluster.local
            subset: canary
          weight: 0

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-a-dr
  namespace: demo-mesh
spec:
  host: app-a.demo-mesh.svc.cluster.local
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary