apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-bg-virtualservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rmiguelito/argocd-example-apps.git
    targetRevision: HEAD
    path: blue-green-with-virtualservice
  destination:
    server: https://192.168.0.5:6443
    namespace: default