apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app: {{ .Release.Name }}
  annotations:
    app: {{ .Release.Name }}      
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- if eq .Values.selectorType "migration" }}
      app: {{ .Release.Name }}
      {{- else }}
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- if eq .Values.selectorType "migration" }}
        app1: {{ .Release.Name }}
        {{- else }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- end }}
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 11
            initialDelaySeconds: 30
          env:
            - name: APP_REVISION
              value: xpto