apiVersion: batch/v1
kind: Job
metadata:
  generateName: wait-before-sync-
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: busybox
        command: ["sh", "-c", "echo Simulando delay... && sleep 3"]
      restartPolicy: Never