apiVersion: batch/v1
kind: Job
metadata:
  name: wait-before-sync
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: busybox
        command: ["sh", "-c", "echo Simulando delay... && sleep 30"]
      restartPolicy: Never