apiVersion: batch/v1
kind: Job
metadata:
  name: delete-hpa
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 90
  template:
    spec:
      serviceAccountName: default
      restartPolicy: Never
      containers:
        - name: delete
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Deleting HPA if exists..."
              echo kubectl delete hpa my-existing-hpa -n {{ .Release.Namespace }} --ignore-not-found