apiVersion: batch/v1
kind: Job
metadata:
  name: delete-hpa
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ttlSecondsAfterFinished: 90
  template:
    spec:
      serviceAccountName: default
      restartPolicy: Never
      containers:
        - name: delete
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Deleting HPA if exists..."
              echo kubectl delete hpa my-existing-hpa -n {{ .Release.Namespace }} --ignore-not-found