apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  source:
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: 1.2.0
    helm:
      parameters:
        - name: api.adminAccount.passwordHash
          # Note: A bcrypt-hashed password will contain `$` characters that
          # MUST each be escaped as `$$`
          value: $2y$10$viA/b/tNSpBE9PYVo2V9JuJic5L24pQ.RHmKttwC/PIJ5k/.lr1pG
        - name: api.adminAccount.tokenSigningKey
          value: aUCkCx9doAfWtsAJndh6zr3JaNYNl1LN
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true