apiVersion: v1
kind: Service
metadata:
  name: my-app-nginx
  namespace: default
  labels:
    app.kubernetes.io/instance: my-app-nginx
spec:
  type: ClusterIP
  selector:
    app: my-app-nginx
  ports:
    - port: 8080
      targetPort: 8080