apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-nginx
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: my-app-nginx
      app.kubernetes.io/instance: my-app-nginx
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-nginx
    scaleDown: progressively
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: {duration: 30s}  # Pause for 30 seconds before proceeding
        - setWeight: 100
        - pause: {duration: 60s}  # Pause for 60 seconds after reaching 100%