apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-nginx
spec:
  replicas: 6
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: {duration: 30s}  # Pause for 30 seconds before proceeding
        - setWeight: 100
        - pause: {duration: 60s}  # Pause for 60 seconds after reaching 100%
  selector:
    matchLabels:
      app: my-app-nginx
      app.kubernetes.io/instance: my-app-nginx
  template:
    metadata:
      labels:
        app: my-app-nginx
        app.kubernetes.io/instance: my-app-nginx
    spec:
      containers:
        - name: my-app-nginx
          image: argoproj/rollouts-demo:blue
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 30
            periodSeconds: 11
            initialDelaySeconds: 60