apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: {}
        - setWeight: 80
        - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: my-app-nginx
      app.kubernetes.io/instance: my-app-nginx
  template:
    metadata:
      labels:
        app: my-app-nginx
        app.kubernetes.io/instance: my-app-nginx
    spec:
      containers:
        - name: my-app-nginx
          image: argoproj/rollouts-demo:green
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 30
            periodSeconds: 11
            initialDelaySeconds: 60