apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-nginx
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: {}
        - setWeight: 80
        - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: my-app-nginx
      app.kubernetes.io/instance: my-app-nginx
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-nginx
    scaleDown: onsuccess